name: Test e2e Deploy to WP Engine
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main


jobs:
  run_action:
    runs-on: ubuntu-latest
    outputs:
      before_version: ${{ steps.deploy.outputs.before_version }}
      after_version: ${{ steps.deploy.outputs.after_version }}
    steps: 
      - uses: actions/checkout@v3
      - run: echo "TODO - use script to bump plugin version number"
      - id: deploy
        name: GitHub Action Deploy to WP Engine
        uses: wpengine/github-action-wpe-site-deploy@v3.0
        with:
          # Deploy vars 
          WPE_SSHG_KEY_PRIVATE: ${{ secrets.WPE_SSHG_KEY_PRIVATE }} 
          WPE_ENV: apmdomino
          # Deploy Options
          SRC_PATH: "wp-content/plugins/my-cicd-plugin"
          REMOTE_PATH: "wp-content/plugins/"
          PHP_LINT: TRUE
          FLAGS: -r --backup --backup-dir=tmp --itemize-changes
          SCRIPT: "wp-content/plugins/my-cicd-plugin/post-deploy.sh"
          CACHE_CLEAR: TRUE
  validate_result:
    runs-on: ubuntu-latest
    needs: run_action
    steps:
      - run: echo TODO - Use action output to check version of test plugin changed from ${{needs.run_action.outputs.before_version}} to ${{needs.run_action.outputs.after_version}} and they are not equal